### ISSUE TITLE
 Why spam? help me fix or tell me that it could be the mistake

### ISSUE THREAD

**Issue by josecuervo2016** [sindresorhus/p-waterfall#2]
this error how fix?  https://pastebin.com/7BrhrFis

There is a plugin that hits me with its waterfall, could you tell me what can be thanks. I give you the list of my lobby plugins

 Plugins :JumpSlime, AnimationLib, WorldEdit, NoRain, Languages, PlayerSettings, Essentials, LobbyProtection, SonezSpawnJoin, SpigotUpdater, IPWhitelist, EssentialsChat, PermissionsEx, FeatherBoard, MicroJump, ViaVersion, NetworkLevels, SuperDeliveryMan, CustomJoinItems, Vault, AnimatedMenu, MysqlEcoBridge, PlayTimeRewards, ProtocolLib, NoCheatPlus, LibsDisguises, Citizens, React, CommandNPC, BossShop, CustomPayloadFixer, CrashFix, GadgetsMenu, HolographicDisplays

**Comment by sindresorhus** [comment]
Because it's not even slightly related to this module. Please try harder next time.
