### ISSUE TITLE
Problems with ESM and electron

### ISSUE THREAD

**Issue by TNing** [sindresorhus/p-waterfall#9]
Hello,

I'm using p-waterfall within electron (Typescript project). With p-waterfall v2.1.1 everything works fine. When I upgrade to v3.0.0 I get the following error:

"require() of ES modules is not supported"

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

You should probably stay on the previous version until Electron support for ESM improves.
